name: Rocket
options:
  deploymentTarget:
    iOS: "13.0"
  bundleIdPrefix: dev.wall-of-death
packages:
  Endpoint:
    path: Libraries/rocket-api/Endpoint
targets:
  Rocket:
    type: application
    platform: iOS
    settings:
      base:
        DEVELOPMENT_TEAM: K677BRB35L
        VERSIONING_SYSTEM: apple-generic
        CURRENT_PROJECT_VERSION: 1
    configFiles:
      Debug: Pods/Target Support Files/Pods-Rocket/Pods-Rocket.debug.xcconfig
      Release: Pods/Target Support Files/Pods-Rocket/Pods-Rocket.release.xcconfig
    sources:
      - path: Rocket
    preBuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        path: /bin/sh
        script: |
          diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
          if [ $? != 0 ] ; then
              # print error to STDERR
              echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." >&2
              exit 1
          fi
          # This output is used by Xcode 'outputs' to avoid re-running this script phase.
          echo "SUCCESS" > "${SCRIPT_OUTPUT_FILE_0}"
        inputFiles:
          - "${PODS_PODFILE_DIR_PATH}/Podfile.lock"
          - "${PODS_ROOT}/Manifest.lock"
        outputFiles:
          - "$(DERIVED_FILE_DIR)/Pods-Rocket-checkManifestLockResult.txt"
    postCompileScripts:
      - name: "[CP] Embed Pods Frameworks"
        path: /bin/sh
        script: '"${PODS_ROOT}/Target Support Files/Pods-Rocket/Pods-Rocket-frameworks.sh"'
      - name: "[CP] Copy Pods Resources"
        path: /bin/sh
        script: |
          if [ -f '"${PODS_ROOT}/Target Support Files/Pods-Rocket/Pods-Rocket-resources.sh"' ]; then
            '"${PODS_ROOT}/Target Support Files/Pods-Rocket/Pods-Rocket-resources.sh"'
          fi
    dependencies:
      - framework: Pods_Rocket.framework
        implicit: true
        embed: false
      - package: Endpoint
